Sucoast Developers Guild operates from TEC Garage (Technology Entrepreneurship Center). TEC Garage is located in the center of St. Petersburg’s thriving business and innovation district, with easy access to beautiful waterfront parks, restaurants, craft breweries and entertainment.

The facility has all necessary equiption to offer an excellent learning expereince, including but not limited to: desks, chairs, projectors, a/v system, high-speed Internet access, whiteboards and a reading library.

The facility includes a classroom to accomodate 30 students, in addition to common areas for social gatherings and breakout sessions.

244 2nd Ave N +
Suite 9 +
St. Petersburg, FL 33701 +
(727) 201-2012

[horizontal]
Business hours:: Monday -- Friday, 9am -- 5pm.

== Observed Holidays

Suncoast Developers Guild observes the following holidays. The facility will be closed and classes will not meet on the these days:

- New Year's Day
- Martin Luther King's Birthday
- Memorial Day
- Independence Day
- Labor Day
- Thanksgiving Day (and following Friday)
- Christmas Day

If you observe holidays not listed here and have concerns about how they might impact your experience, please contact us.
