== Program Outline

=== Fundamentals

- Background and Basics
  * Setting up a development environment
  * Getting comfortable with the text editor
  * Version Control & Git
  * Web basics: HTML & CSS
  * How does the internet work? - DNS, HTTP/HTTPS, browsers, etc.
- Programming Fundamentals
  * Syntax
  * Methods and functions
  * Control structures
- Paradigms
  * Objects, constructors, and object-oriented programming
  * Anonymous functions
  * Scope, closures, and `this`
  * Asynchronous programming; callbacks and promises

=== Front-end Frameworks

- Modern JavaScript tooling
  * webpack
  * ES2015+, transpiling, modules
  * Deploying
- React
  * Component driven design
  * Routing
  * Managing complex state
- Intermediate Web Concepts
  * Using data (via JSON)
  * Intermediate CSS
  * APIs, AJAX, and REST

=== Back-end Frameworks

- Working with servers
  * Responding to requests
  * REST + APIs
  * Templating Engines
  * Deploying
  * Model-View-Controller
- Working with data
  * Database Basics
  * SQL
  * Migrations
  * Object Relational Mapping

== Classwork and Homework

[horizontal]

Daily Content:: Reading and video content relating information about an idea. Daily Content is given before each class day. It's released by the end of lunch on the previous class day, i.e. Monday's content will be released Friday afternoon. Content will consist of a variety of mediums and sources.

Lab Activity:: _Ungraded_ practice implementing a partially complete idea. It should closely follow examples in the daily content. The student is given most of the idea, similar to filling in blanks. Lab Activities are given during class Monday through Thursday, and are completed the same day.

Assignment:: _Graded_, small projects implementing a whole idea it should require an abstraction of the idea presented earlier, as well as integrated with previously covered concepts. The student is usually given _some_ boilerplate to start the assignment. Assignments are given Monday through Wednesday in the afternoon, and due the following morning, before class.

Projects:: _Graded_, mid-sized multi-day (weekend) assignments that build on ideas presented during the week. Usually built from scratch, but may span building and expanding the same application over multiple weeks. A Project is given on Thursday afternoon, and due the following Monday, before class.

Capstone Project:: A large project that represents the culmination of a student's learning in the program. The project is started 4-6 weeks into the curriculum and is due before graduation at the end of the program. The student will have regular milestone checkins with the instructors to receive guidance on the project. The project's content, design, and scope is determined by the student, subject to instructor approval.

All graded work is comprised of three modes. Students must complete Explorer mode while Adventure and Epic modes provide students additional practice and learning opportunities.

[horizontal]

Explorer:: A focus on exploring the core concepts, as presented in the content and lectures.

Adventure:: A deeper dive into ideas not necessarily covered in class and will usually require research and investigation.

Epic:: Requires the student to tie abstract ideas together and bring professional levels of polish and effort to the assignment or project.

Career support is a mandatory part of the curriculum.

== Definition of Clock Hours

Clock Hours are defined as not less than 50 minutes of: class, lecture, or instructor-supervised laboratory time. The breakdown of clock hours for full program is as follows:

$$
\begin{aligned}
180~ & \text { Theory Hours } \\
\underline{+~216~} & \text{ Lab Hours } \\
396~ & \text{ Total Clock Hours }
\end{aligned}
$$

== Transfer of Academic Credit

We do not accept any transfer credits or clock hours and we cannot offer any academic credit when you complete the program. Transfer of clock hours earned at Suncoast Developers Guild is at the discretion of the accepting institution.
