TODO: Re-write some of this, it was lifted heavily from TIY catalog

Suncoast Developers Guild uses pass or fail grading system for assignments and projects. Completion of the program is depends on a demonstrated proficiency of the curriculum as determined by your instructor.

Instructors evaluate student performance with the program director on a bi-weekly basis. If the evaluation shows that a student is not performing well, instructors and the program director may meet with the student to discuss thier progress, and determine steps to improve performance.

If instructors and the program director must have more than two (2) meetings with a student regarding poor performance, that student may be asked to leave the current program.

If you disagree with any evaluation, you may contact your instructor, the program director, or file a complaint following procedures outlined under the section titled "Complaints."

NOTE: You may not re-enroll in the same program semester if you dropout, or are asked to leave. You must apply for a new program, and follow the same entrance requirements as if you are a new student.

== Absences and Tardies

- If you are determined to have two (2) tardies in one (1) week, it will be counted as an absence.
- If you miss more than six (6) lectures, or tally more than six (6) absences, .
- If will be late to a lecture, give your instructor reasonable notice, by no later than 9:30 AM. If you are late to a lecture, and did not give your instructor notice, it will be at the instructor's discretion whether to count you as tardy.
- You will not be allowed to make-up any of the missed attendance.



We understand that issues arise; _life happens_. Communicating with faculty and staff will allow us to make appropriate adjustments needed to keep you on track.

== Graduation Requirements

Students understand that in order to graduate from the program and to receive a certificate, they must successfully complete the required number of scheduled clock hours as specified in the catalog and on the Student Enrollment Agreement, satisfactorily pass assignments and satisfy all financial obligations to the School.

== Certificate of Completion

When you complete the program, and have satisfied all assignment requirements, we will award you a Certificate of Completion.