TODO: Re-write some of this, it was lifted heavily from TIY catalog

Suncoast Developers Guild uses pass or fail grading system for assignments and projects. Completion of the program is depends on a demonstrated proficiency of the curriculum as determined by your instructor.

Instructors evaluate student performance with the program director on a bi-weekly basis. If the evaluation shows that a student is not performing well, instructors and the program director may meet with the student to discuss thier progress, and determine steps to improve performance.

If instructors and the program director must have more than two (2) meetings with a student regarding poor performance, that student may be asked to leave the current program.

If you disagree with any evaluation, you may contact your instructor, the program director, or file a complaint following procedures outlined under the section titled "Complaints."

NOTE: You may not re-enroll in the same program semester if you dropout, or are asked to leave. You must apply for a new program, and follow the same entrance requirements as if you are a new student.

== Absences and Tardies

Being late to the beginning of class is disruptive not only to you, but to your classmates. If you know that you will be late to a lecture, give your instructor reasonable notice prior to the class commencing. If you are late to a lecture, and did not give your instructor notice, it will be up to the instructor's discretion whether to count you as tardy.

- If you are determined to have two (2) tardies in one (1) week, it will be counted as an absence.
- If you miss more than six (6) lectures, or tally more than six (6) absences, it will be difficult for you to keep up with the course content, and it will be difficult for us to provide a strong recommendation for you during job placement.

We will have ongoing discussions with anyone falling behind to determine the appropriate adjustments needed to get back on track, or to potentially part ways if recovery is unlikely. _However_, we understand that conflicts arise. Just talk to us and let us know what's going on as early as possible so we can make sure you are keeping up with the course and getting your work done. You will not be allowed to make-up any of the missed attendance.

== Graduation Requirements

Students understand that in order to graduate from the program and to receive a certificate, they must successfully complete the required number of scheduled clock hours as specified in the catalog and on the Student Enrollment Agreement, satisfactorily pass assignments and satisfy all financial obligations to the School.

== Certificate of Completion

When you complete the program, and have satisfied all assignment requirements, we will award you a Certificate of Completion.