== Daily Schedule

[cols="h,,",options="header"]
|===
|          | Monday -- Thursday | Friday
| 09:00 AM | Instructor's Hour  | 
| 10:00 AM | Class              | Career Support Lecture
| 11:00 AM | "                  | Weekly Review (or extended Career Support)
| 12:00 PM | Lunch              | Lunch
| 01:00 PM | Lab                | Lab
| 02:00 PM | Review at Two      | Huddles
| 03:00 PM | Lab                | End of Day (optional social time)
| 04:00 PM | "                  | 
| 05:00 PM | End of Day         | 
|===

== Classwork and Homework

Daily Content:: Reading and video content relating information about an idea. Daily Content is given before each class day. It's released by the end of lunch on the previous class day, i.e. Monday's content will be released Friday afternoon. Content will consist of a variety of mediums and sources.

Lab Activity:: _Ungraded_, practice implementing a partially complete idea it should closely follow examples in the daily content given most of the idea, just filling in blanks. Lab Activities are given Monday through Thursday, and are completed the same day.

Assignment:: _Graded_, a small project implementing a whole idea it should require an abstraction of the idea presented earlier, as well as integrated with previously covered concepts usually given _some_ boilerplate. Assignments are given Monday through Wednesday in the afternoon, and due the following morning, before class.

Projects:: _Graded_, larger multi-day (weekend) assignments that build on ideas presented during the week. Usually built from scratch, but may span building and expanding the same application over multiple weeks. A Project is given on Thursday afternoon, and due the following Monday, before class.

Graded work is assigned tasks over three modes:

"Explorer" mode:: A focus on exploring the core concepts, as presented in the content and lectures.
"Adventure" mode:: A deeper dive into ideas not necessarily covered in class and will usually require research and investigation.
"Epic" mode:: Requires the student to tie abstract ideas together and bring professional levels of polish and effort to the assignment or project.

Career support is a mandatory part of the curriculum.

== Computer requirements

Suggested computer is a Mac less than two years old.

*Minimum requirements:* 2014 or newer (find specific year/models)
PC laptops can be approved for class use on a case by case basis.
Approval is part of the interview process.
