== Code of Conduct

Suncoast Developers Guild is dedicated to providing a harassment-free educational experience for everyone, regardless of gender, sexual orientation, disability, physical appearance, body size, race, or religion.

The institution does not tolerate harassment in any form. Sexual language and imagery is not appropriate for any venue related to school-sponsored activity. _A student violating these rules may be sanctioned or expelled at the discretion of the institution_. Harassment includes, but is not limited to, offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of lectures or other events, inappropriate physical contact,and unwelcome sexual attention.

NOTE: If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of the faculty or staff immediately.

Students asked to stop any harassing behavior areexpected to comply immediately. If a student engages in harassing behavior, the institution may take any action it deems appropriate, including warning the offender or expulsion from the school.
