== Evaluation

Suncoast Developers Guild uses pass or fail grading system for Assignments and Projects. Completion of the program depends on a demonstrated proficiency of the curriculum as determined by your instructor. Instructors evaluate trainee performance with the Program Director on a bi-weekly basis. If the evaluation shows that a trainee is not performing well, instructors may meet with the trainee to discuss their progress, and determine steps to improve performance.

=== Absences and Tardies

- If you are determined to have two (2) tardies in one (1) week, it will be counted as an absence.
- If you miss more than six (6) lectures, or tally more than six (6) absences, you may not be eligible for completion of the program
- If you will be late to a lecture, give your instructor reasonable notice, by no later than 9:30 AM. If you are late to a lecture, and did not give your instructor notice, it will be at the instructor's discretion whether to count you as tardy.
- You will not be allowed to make-up any of the missed attendance.

We understand that issues arise; _life happens_. Keeping communication open with faculty and staff will allow us to make appropriate adjustments needed to keep you on track.

=== Completion Requirements

In order to complete the program a trainee must successfully meet the absences and tarty policy, satisfactorily pass eighty percent of assignments and projectsa and adhere to the Code of Conduct

