== Evaluation

Suncoast Developers Guild uses ((pass or fail)) ((grading)) system for ((Assignments)) and ((Projects)). Completion of the program is depends on a demonstrated proficiency of the ((curriculum)) as determined by your instructor.

Instructors evaluate student performance with the ((Program Director)) on a bi-weekly basis. If the ((evaluation)) shows that a student is not performing well, instructors and the ((Program Director)) may meet with the student to discuss their progress, and determine steps to improve ((performance)).

If instructors and the ((Program Director)) must have more than two (2) meetings with a student regarding poor performance, that student may be asked to leave the current program.

If you disagree with any evaluation, you may contact your instructor, the ((Program Director)), or file a complaint following procedures outlined under the section titled "Complaints."

NOTE: You may not re-enroll in the same program semester if you dropout, or are asked to leave. You must apply for a new program, and follow the same entrance requirements as if you are a new student.

=== Absences and Tardies

- If you are determined to have two (2) tardies in one (1) week, it will be counted as an ((absence)).
- If you miss more than six (6) ((lectures)), or tally more than six (6) absences, you may not be eligible for ((Career Support)) services, at the discretion of the ((Program Director)).
- If will be late to a lecture, give your instructor reasonable notice, by no later than 9:30 AM. If you are late to a lecture, and did not give your instructor notice, it will be at the instructor's discretion whether to count you as ((tardy)).
- You will not be allowed to make-up any of the missed attendance.

We understand that issues arise; _life happens_. Keeping ((communication)) open with faculty and staff will allow us to make appropriate adjustments needed to keep you on track.

=== Graduation Requirements

In order to graduate (((graduation))) from the program and to receive a ((certificate)), they must successfully complete the required number of scheduled clock hours as specified in the catalog and on the Student Enrollment Agreement, satisfactorily pass eighty percent of assignments and projects, and satisfy all financial obligations to the School.

=== Certificate of Completion

When you complete the program, and have satisfied all requirements, we will award you a *((Certificate of Completion))*.
