== Notices

Suncoast Developers Guild, Inc. is a corporation registered with the State of Florida.

Jason L Perry, CEO +
Toni Warren, President


---

Suncoast Developers Guild, Inc. does not and shall not discriminate on the basis of race, color, national origin, religion, creed, age, disability, military or veteran's status, sexual orientation, gender, gender identity, or gender expression, in any of its activities or operations. These activities include, but are not limited to: hiring and firing of staff, selection of volunteers and vendors, and provision of services, administration of its educational policies, admissions policies, scholarships, and other programs. We are committed to providing an inclusive and welcoming environment for our staff, trainees, volunteers, and members.

---

Suncoast Developers Guild, Inc. is an equal opportunity employer. We will not discriminate and will take affirmative action measures to ensure against discrimination in employment, recruitment, advertisements for employment, compensation, termination, upgrading, promotions, and other conditions of employment against any employee or job applicant on the bases of race, color, national origin, religion, creed, age, disability, military or veteran's status, sexual orientation, gender, gender identity, or gender expression.
