== Curriculum

=== Program Description

This course of instruction prepares individuals for entry-level jobs as front-end or back-end engineers, and web developers. Graduates will be able find employment with companies who build and maintain their own websites and web applications (i.e. product work), or with agencies that produce websites and web applications for other companies (i.e. client work).

Students will learn client-side (front-end) technology: HTML, CSS, and JavaScript as well as server-side (back-end) technology such as .NET or Ruby on Rails. At the end of the course, students will be able to create beautiful, fully functional websites backed by databases and server-side applications.

=== Definition of Clock Hours

Clock Hours are defined as not less than 50 minutes of: class, lecture, or instructor-supervised laboratory time. The breakdown of clock hours for full program is as follows:

> 180 Theory Hours + 216 Lab Hours = 396 Total Clock Hours

=== Transfer of Academic Credit

We do not accept any transfer credits or clock hours and we cannot offer any academic credit when you complete the program. Transfer of clock hours earned at Suncoast Developers Guild is at the discretion of the accepting institution.

<<<
